# Generated by Django 5.0.4 on 2024-05-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_confirmed',
        ),
    ]
